
UPDATE public.ref_migration_tracker SET notes = CASE priority_rank
  WHEN 5  THEN 'No ref table. Shared enum with task_pipeline.priority (#9). Create ref once, apply to both.'
  WHEN 7  THEN 'No ref table. Batch all 4 task_pipeline cols together.'
  WHEN 8  THEN 'No ref table. Has DEFAULT ''manual'' on column.'
  WHEN 9  THEN 'No ref table. Shared enum with hh_deals.priority (#5). Has DEFAULT ''Medium'' on column.'
  WHEN 10 THEN 'No ref table. Has DEFAULT ''GNF Deal'' on column. auth_rls_initplan lint flagged on this table.'
  WHEN 12 THEN 'No ref table. Same 3 views as #11. Batch with #11.'
  WHEN 15 THEN 'No ref table. Batch with calling_year (#16).'
  WHEN 17 THEN 'No ref table. Views reference this column as store_state and primary_account_state.'
  WHEN 20 THEN 'Array col → junction table pattern. No ref table.'
  WHEN 21 THEN 'Array col → junction table pattern. No ref table. Actual table name is brand_contacts_table.'
  WHEN 22 THEN 'No ref table. Type name has spaces — watch cast syntax. 2 views affected.'
  WHEN 23 THEN 'No ref table. udt_name has a trailing space (''Fulfillment Method '') — exact name required in cast.'
  WHEN 24 THEN 'No ref table.'
  WHEN 26 THEN 'No ref table. Shared enum with master_promo_data.effective_promo_year (#40).'
  WHEN 27 THEN 'Typo in enum type name: promo_submissinon_status (double n). Has DEFAULT ''Requested'' on column.'
  WHEN 28 THEN 'No ref table.'
  WHEN 29 THEN 'No ref table. Column is NOT NULL — safe mode required.'
  WHEN 30 THEN 'No ref table.'
  WHEN 31 THEN 'No ref table. Type name has spaces — watch cast syntax.'
  WHEN 32 THEN 'No ref table.'
  WHEN 33 THEN 'No ref table.'
  WHEN 34 THEN 'Array col → junction table pattern. No ref table. Column name is private_label_bulk_and__or_food_service.'
  WHEN 35 THEN 'No ref table. Has DEFAULT on column. Shared enum with hh_account_experts.status (#36). Migrate both in one transaction.'
  WHEN 36 THEN 'No ref table. Shares enum with hh_community_experts.status (#35).'
  WHEN 37 THEN 'No ref table. Has DEFAULT ''Pending Review'' on column.'
  WHEN 39 THEN 'No ref table. Shared enum with brand_promo_requests.effective_promo_month (#25).'
  WHEN 40 THEN 'No ref table. Shared enum with brand_promotions.promo_year (#26).'
  WHEN 41 THEN 'No ref table. Column is NOT NULL — safe mode required.'
  WHEN 42 THEN 'No ref table. Column is NOT NULL with DEFAULT ''unread''.'
  WHEN 44 THEN 'No ref table.'
  WHEN 45 THEN 'No ref table.'
  WHEN 46 THEN 'No ref table.'
  WHEN 47 THEN 'No ref table. Shared enum with principal_list_product_specs. Batch all spec_price_sheet cert cols together.'
  WHEN 48 THEN 'No ref table. Shared enum with principal_list_product_specs.transport.'
  WHEN 49 THEN 'No ref table. Shared enum with principal_list_product_specs.uom.'
  WHEN 50 THEN 'No ref table.'
  WHEN 51 THEN 'No ref table. specs_certification_options used across 12+ cols in spec_price_sheet and 11 in principal_list_product_specs. Batch all cert cols together. spec_price_sheet has duplicate *_status cols (gluten_free_status, kosher_status etc.) — dedup during migration.'
  WHEN 52 THEN 'No ref table. Batch with #51.'
  WHEN 53 THEN 'No ref table. Batch with #51.'
  WHEN 54 THEN 'No ref table. Batch with #51.'
  WHEN 55 THEN 'No ref table. Batch with #51.'
  WHEN 56 THEN 'No ref table. Batch with #51.'
  WHEN 57 THEN 'No ref table. Batch with #51.'
  WHEN 58 THEN 'No ref table. Batch with #51.'
  WHEN 59 THEN 'No ref table. Batch with #51.'
  WHEN 60 THEN 'No ref table. Batch with #51.'
  WHEN 61 THEN 'No ref table. Batch with #51.'
  WHEN 62 THEN 'No ref table.'
  ELSE notes
END
WHERE priority_rank <= 62;
;